Lambda-School-Labs/ping-catcher-be

server.js
Initial Commit of the project. Dependencies installed, and set up.
Initial Commit / Push.
=> Aaron andersen

server.js
Reverts Lambda-School-Labs/ping-catcher-be#2
=> Revert "Aaron andersen"

index.js, package-lock.json, package.json, slack/api.js
Added a slack router for future slack api http requests and added code to catch events from slack.
- [x ] New feature (non-breaking change which adds functionality)
- [ x] Incomplete/work-in-progress, PR is for discussion/feedback
- [ x] Tested using mock projects I created.
- [x ] Tested in ping-catcher-be using localhost.
=> created slack router and added slack event listener

knexfile.js
Fixed Knex Migrations 
Needed to connect branch to Heroku in order to get our Knex Migrations working. 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] Complete, tested, ready to review and merge
Has not been fully tested but need to push in order to test. 
- [ x] My code follows the style guidelines of this project
- [x ] My code has been reviewed by at least one peer
- [ x] I have made corresponding changes to the documentation
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests …
=> fixed migrations directory

migrations/20200617183432_Slack_User.js
Added Migration for Slack_User
)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] Complete, but not tested (may need new tests)
No
- [x ] My code follows the style guidelines of this project
- [ x] My code has been reviewed by at least one peer
- [x ] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
=> Adding Slac_User Migration

migrations/20200617183432_Slack_User.js
Fixed typo on code
Updated typo
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, but not tested (may need new tests)
no
- [x ] My code follows the style guidelines of this project
- [x ] My code has been reviewed by at least one peer
- [x ] I have made corresponding changes to the documentation
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
=> fixed typo

migrations/20200617183432_Slack_User.js
Found another typo it has been fixed. 
Typo Fix
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] Complete, but not tested (may need new tests)
No
- [x ] My code follows the style guidelines of this project
- [x ] My code has been reviewed by at least one peer
- [ x] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ x] There are no merge conflicts
=> Fixed typo v 2

migrations/20200617191114_Events.js
Added Event Migrate table
Addtion
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Complete, but not tested (may need new tests)
-
no
- [x ] My code follows the style guidelines of this project
- [x ] My code has been reviewed by at least one peer
- [x ] I have made corresponding changes to the documentation
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts
=> Event migrate

index.js, package.json
Added body parser to decode slack challenge
=> added body parser

index.js
Added express.json in index file.
Should read incoming objects as JSON.
=> added express.json to interpret incoming objects

events/challenge-middleware.js, events/eventsModel.js, events/eventsRouter.js, index.js, server.js
=> Style add server.js

events/eventsModel.js, events/eventsRouter.js
=> upated events model return

events/eventsRouter.js
changed route post back to promise based
=> changed post back to promise based

events/eventsModel.js, events/eventsRouter.js
Changed event model to slack_user_id
=> changed event model

migrations/20200617191114_Events.js
Removed accidental number in migration
=> removed 255 from slack user id

events/eventsModel.js
Editing database model to accept users as numbers
=> changing user to a number to store in db

events/eventsModel.js, migrations/20200617191114_Events.js
Added a column in the database to store slack usernames
=> added column slack_username

events/eventsModel.js
Edited the events model in order to store the username as a string
=> changed user to slack_username to store it as a string

events/eventsModel.js, events/eventsRouter.js, events/usersModel.js, migrations/20200616203104_01users.js, migrations/20200617183432_Slack_User.js
Added a users model to handle verifying new/existing users
=> Verifying users

knexfile.js, migrations/20200617183432_02Slack_User.js, migrations/20200617191114_03Events.js, migrations/20200625212106_04Rankings.js
Fixing existing migrations to prepare for new tables in database
=> edited existing migrations and added ssl for postgres

knexfile.js
=> fixed migration directory

migrations/20200617183432_Slack_User.js, migrations/20200617191114_Events.js
=> fixing knex migration mistake

events/eventsRouter.js, events/rankingModel.js, events/threadRankingModel.js, events/usersModel.js, migrations/20200625212106_04Rankings.js
Added ranking model and thread ranking model
=> adding ranking model and thread ranking model

events/eventsModel.js
Working on the events model to get events to automatically populate the database.
-[x] My code follows the style guidelines of this project
=> editing the events model add function

events/eventsModel.js
Added event model to check for existing users
=> added a find function to check for user id

events/eventsModel.js
Testing functionality of the database
=> testing the add function in the event model

events/eventsModel.js, events/slackUserModel.js
Added a function to find by id
=> add findById function in slack user model

events/eventsModel.js
Testing to see if ids are being passed through
=> testing if user ids are being passed through

events/eventsModel.js
Testing to see if user ids are being passed through
=> adding code to my blank pull request

events/eventsModel.js
Changed the event model to get the id
=> changed the event model to reflect the id being auto returned

events/eventsModel.js
fixing an error in event model
=> fixing error

events/slackUserModel.js
Added async await in the slack user model
=> added async in the slack user model

events/slackUserModel.js
Made the await into a variable to return later
=> changed async to a variable

migrations/20200625212106_04Rankings.js, migrations/20200708214110_05meta_event.js
=> added meta event table

events/eventsModel.js, events/eventsRouter.js, migrations/20200708214110_05meta_event.js
Move slack user id from model to router
=> moved slack user id to router

events/eventsModel.js, events/eventsRouter.js
Added functionality to save events to db
=> displaying messages

events/eventsModel.js
Removed slack user id from model
=> removed slack id

database/db-config.js, events/eventsRouter.spec.js, knexfile.js, package-lock.json, package.json
Created a database to run tests
=> adding test database

database/db-config.js
Changed the database config to reflect environment variables from heroku
=> changing to environment variable

events/eventsRouter.spec.js, knexfile.js, package-lock.json, package.json, server.spec.js
Testing to see if my testing environment is set up correctly
=> testing the testing

.github/workflows/ci.yml, .gitignore
Setup CodeClimate yml file (ci.yml)
Should complete code coverage base setup.
=> ci: setup codeclimate

events/eventsModel.js, events/eventsRouter.js, knexfile.js
Added code to check database for existing users, if doesn't exist add user and then add event, if does exist, add event
=> edited code to check for existing user and add event

events/eventsRouter.js, events/slackUserModel.js
Changed the findByName id to slack_user
=> changed id to slack_user

events/eventsRouter.js
Changed slack_user to reflect event.user
=> changed slack user to event.user

events/challenge-middleware.js, events/eventsRouter.js
Adding console logs to test function
=> adding console logs to test post request

events/eventsRouter.js
=> added logging for slack_user_id

events/eventsRouter.js
=> changed exists id to a number

events/eventsRouter.js
Added a check for undefined id
=> added second check for exists id

events/eventsRouter.js, migrations/20200617183432_02Slack_User.js, migrations/20200617191114_03Events.js
=> Event router

events/eventsModel.js, events/eventsRouter.spec.js, events/slackUserModel.js, migrations/20200710225507_05Rankings.js
Editing ranking table to be a string.
=> edited rankings migration

events/eventsModel.js, events/eventsRouter.js, events/eventsRouter.spec.js, events/slackUserModel.js, events/usersModel.js, index.js, knexfile.js, package.json, server.js
Changed event router to add new user to database if doesn't exist
=> changed event router to add new user

api/events/eventsRouter.js, api/slackUsers/slackUserModel.js, api/slackUsers/slackUserRouter.js, api/users/usersRouter.js, knexfile.js, package.json
Making changes to the API routes
=> making changes to the api routes

api/slackUsers/slackUserModel.js, api/slackUsers/slackUserRouter.js, migrations/20200617183432_02Slack_User.js, migrations/20200617191114_03Events.js, server.js
Changed slack_user column name from slack_user to slack_username
=> changed slack_user column name

api/events/eventsRouter.js, migrations/20200710225507_05Rankings.js
Changes slack_user in thread rankings table to slack_username
=> changed slack user to slack username in rankings table

api/events/eventsRouter.js, api/slackUsers/slackUserModel.js, api/slackUsers/slackUserRouter.js
changed the remainder of slack users to slack username
=> changed the remainder of slack users to slack username

api/events/eventsModel.js, api/events/eventsRouter.js, api/slackUsers/slackUserModel.js
Re-wrote the endpoint to add events into the database factoring in the slack_username changes
=> rewrote the adding event route

api/slackUsers/slackUserModel.js, api/slackUsers/slackUserRouter.js
Adding user function works, this push should get the add slack user function to work
=> adding user now works, working on adding slack user

api/slackUsers/slackUserModel.js, api/slackUsers/slackUserRouter.js
Edited the slack user find by name route
=> hashed out the find by name route in slack users

api/events/eventsRouter.js
edited the events Router to destructure the incoming nested object
=> edited the events Router to destructure the incoming nested object

api/events/eventsModel.js, api/events/eventsRouter.js
Added console logs and api info to see what data we are getting
=> added tests to see what data is being returned

api/events/eventsModel.js, api/events/eventsRouter.js, api/middleware/challenge-middleware.js
Changed destructuring and added more logs to try and see the structure of the data
=> added more logs to see structure of data

api/events/eventsRouter.js
Fixed destructuring error and logging event
=> fixed destructuring error and logging event

api/events/eventsModel.js, api/events/eventsRouter.js
changed the structure of the event to match the database table
=> changed the structure of the event to match the database table

api/events/eventsModel.js
Changed database call to return id
=> changed database call to return id

api/events/eventsModel.js, api/events/eventsRouter.js
moved users add function to the catch statement
=> moved users add function to the catch statement

api/events/eventsRouter.js
=> logging userID

api/events/eventsRouter.js, api/users/usersModel.js
finished writing the event router add function
=> finished writing the event router add function

api/events/eventsRouter.js
fixed error when adding to the events table
=> fixed error when adding to the events table

api/events/eventsRouter.js, api/slackUsers/slackUserModel.js
reformatted event router to check existing users in the database
=> reformatted event router to check existing users in the database

api/events/eventsRouter.js
re-formatted back to .catch functions rather than ternary
=> re-formatted back to .catch functions rather than ternary

api/events/eventsRouter.js
changed the slack user add function to take in correct params
=> changed the slack user add function to take in correct params

api/events/eventsModel.js, api/events/eventsRouter.js, api/rankings/threadRankingModel.js, api/rankings/threadRankingRouter.js, api/slackUsers/slackUserModel.js, knexfile.js, server.js
Added a thread ranking model to do a get request based on text that the user passes in
=> Testing out round 1 of subscriptions

api/events/eventsModel.js, api/events/eventsRouter.js, api/metaEvents/metaEventRouter.js, api/metaEvents/metaEventsModel.js, api/rankings/rankingModel.js, api/rankings/threadRankingModel.js, api/rankings/threadRankingRouter.js, migrations/20200710225427_04meta_events.js, server.js
Creating logic to add subscriptions for users
=> Subscriptions

api/metaEvents/metaEventRouter.js
Looking at the structure of the incoming event
=> logging the req.body

README.md, api/metaEvents/metaEventRouter.js, api/sse/sseModel.js, api/sse/sseRouter.js, server.js
Changed status code to clear form
=> Status code

api/metaEvents/metaEventRouter.js, migrations/20200617183432_02Slack_User.js
=> changed status code, added new column to slack user table

migrations/20200617183432_02Slack_User.js
=> changing migrations

api/sse/sseRouter.js
=> edited imports in sseRouter

migrations/20200811223649_06slackUser.js
=> Altering slack user table

migrations/20200811223649_06slackUser.js
=> fixed typo in alter table

api/metaEvents/metaEventRouter.js
=> setting headers in metaEvent

api/metaEvents/metaEventRouter.js
editing headers for ping-catcher
=> editing headers for ping-catcher

api/sse/sseRouter.js
changing headers to include ping-catcher
=> changing headers to include ping-catcher

api/metaEvents/metaEventRouter.js, api/sse/sseRouter.js
Created metaEvent router using the incoming form object
=> Created metaEvent router using the incoming form object

api/events/eventsRouter.js
=> adding ranking id as null

api/events/eventsRouter.js, api/slackUsers/slackUserModel.js
=> added ranking id in model

api/events/eventsRouter.js
=> working on event router

api/events/eventsRouter.js
adding console log for slack user error
=> adding console log for slack user error

api/events/eventsRouter.js, migrations/20200811223649_06slackUser.js
=> editing slack user migration

migrations/20200811223649_06slackUser.js
=> Working on migrations

migrations/20200811223649_06slackUser.js
removed drop table on the new migration
=> removed drop table on the new migration

migrations/20200617183432_02Slack_User.js, migrations/20200710225507_05Rankings.js
=> moving table drops to fix bug

migrations/20200617183432_02Slack_User.js
one final drop change to fix bug
=> one final drop change to fix bug

migrations/20200710225427_04meta_events.js
=> fixed typo in metaevent

api/metaEvents/metaEventsModel.js, migrations/20200617183432_02Slack_User.js
Console logging sub and changing destructuring
=> Logging sub

api/metaEvents/metaEventRouter.js, migrations/20200617183432_02Slack_User.js
Changed thread ranking functionality
=> Thread ranking

api/metaEvents/metaEventRouter.js, api/rankings/rankingModel.js, api/slackUsers/slackUserModel.js, migrations/20200617183432_02Slack_User.js
Cleaning up code in metaEventRouter
=> Cleaning code

api/metaEvents/metaEventRouter.js, api/metaEvents/metaEventsModel.js, migrations/20200617183432_02Slack_User.js
changed meta event find method and logging event key
=> Json parse

migrations/20200617183432_02Slack_User.js, migrations/20200818212321_07meta_event.js
=> Alter table

api/metaEvents/metaEventRouter.js, api/metaEvents/metaEventsModel.js
=> console logging rank response

api/rankings/rankingModel.js
Checking if ranking is undefined
=> Checking if ranking is undefined

api/metaEvents/metaEventRouter.js, api/rankings/rankingModel.js
changed find by id into an async function
=> changed find by id into an async function

api/metaEvents/metaEventRouter.js, api/slackUsers/slackUserModel.js
=> working on adding meta events

api/metaEvents/metaEventRouter.js
changed rank resposne to an array
=> changed rank resposne to an array

api/metaEvents/metaEventRouter.js
adding meta event using a try catch block
=> adding meta event using a try catch block

api/rankings/rankingModel.js
added brackets in ranking model
=> added brackets in ranking model

api/rankings/rankingModel.js
adding first method in ranking model
=> adding first method in ranking model

api/metaEvents/metaEventRouter.js, api/rankings/rankingModel.js
=> getting first item in array

api/metaEvents/metaEventRouter.js, api/slackUsers/slackUserModel.js
=> updating by slack user name

api/rankings/threadRankingModel.js
switched db table from rankings to thread rankings
=> switched db table

api/metaEvents/metaEventRouter.js, api/metaEvents/test.js
converted add meta event to an async function
=> converted add meta event to an async function

api/metaEvents/metaEventRouter.js
changed sub response to addMeta
=> chaged sub response to addMeta

api/metaEvents/metaEventsModel.js
=> fixing a parsing bug

api/metaEvents/metaEventRouter.js
=> fixed bracket bug

api/metaEvents/metaEventRouter.js
=> changed null to empty string

api/metaEvents/metaEventRouter.js, api/metaEvents/metaEventsModel.js
working on adding thread rankings
=> working on adding thread rankings

api/metaEvents/metaEventRouter.js, api/rankings/threadRankingModel.js
=> logging behavior

api/metaEvents/metaEventRouter.js
grabbing first index of addMeta array
=> grabbing first index of addMeta array

api/metaEvents/metaEventRouter.js
added else block to catch rank response
=> added else block to catch rank response

api/metaEvents/metaEventRouter.js
setting ranking id as rank response.id
=> setting ranking id as rank response.id

api/metaEvents/metaEventRouter.js
sending nickname from parsed object
=> sending nickname from parsed object

api/metaEvents/metaEventRouter.js, api/metaEvents/metaEventsModel.js, api/rankings/rankingRouter.js, api/rankings/threadRankingModel.js
=> adding subscription endpoints

api/rankings/rankingRouter.js
created async functions for get methods
=> created async functions for get methods

api/rankings/rankingRouter.js
=> changed endpoint names

api/rankings/rankingRouter.js
=> adding id after rank response

api/rankings/rankingRouter.js
removed first index in ranking id
=> removed first index in ranking id

api/rankings/rankingRouter.js, api/rankings/threadRankingModel.js
=> changed to rankings_id

api/rankings/rankingRouter.js
=> changed to rankResponse.id

api/rankings/rankingRouter.js
=> removed first index
